#!/bin/bash

current_dir=$(pwd)

parent_dir=$(dirname "$current_dir")

for file in "$current_dir"/*.html; do

    filename=$(basename "$file")
    destination="$parent_dir/$filename"

 if [ ! -e "$destination" ] || [ "$file" -nt "$destination" ]; then
        cp "$file" "$destination"
        echo "Copied $file to $destination"
    else
        echo "Skipped $file"

